services:
  - type: web
    name: gotgaibot1
    runtime: go
    repo: https://github.com/yourusername/yourrepo
    buildCommand: go build -tags netgo -ldflags "-s -w" -o app ./cmd/app
    startCommand: ./app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_LEGEND
        sync: false